# Generated by Django 5.1.7 on 2025-06-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "lastname",
                    models.CharField(max_length=200, verbose_name="sobrenome"),
                ),
                ("cpf", models.CharField(max_length=15, unique=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")], max_length=1
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("date_of_birth", models.DateField(verbose_name="data de nascimento")),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Ativo"), ("P", "Pendente"), ("I", "Inativo")],
                        default="A",
                        max_length=1,
                        verbose_name="Status Do Aluno",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("last_status_change", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
