# Generated by Django 5.1.7 on 2025-06-30 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Aluno",
            new_name="Students",
        ),
        migrations.RenameField(
            model_name="students",
            old_name="sexo",
            new_name="sex",
        ),
    ]
