# Generated by Django 5.1.7 on 2025-07-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_rename_aluno_students_rename_sexo_students_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="last_status_change",
            field=models.DateField(auto_now=True),
        ),
    ]
