[build]
builder = "DOCKERFILE"

[deploy]
releaseCommand = "python manage.py migrate --no-input"
startCommand = "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
