[build]
builder = "DOCKERFILE"

[deploy]
releaseCommand = "python manage.py migrate --no-input"
startCommand = "gunicorn --workers 1 --threads 2 --timeout 60 --log-level=debug core.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
